version: '3'
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - host
    ports:
      - 80:80
